#!/system/xbin/bash
#hey pemalas? Ubah author gw doain semoga emak bapak lu mati dan lu sial 49 tahun dan lu mandul!!!!!
clear
echo "\033[1;31m ┏━╮╭━┓ ╭━━━━━━╮\033[31;0m    ●▬▬▬▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬▬▬▬●
\033[91m ┃┏┗┛┓┃╭┫\033[92mC3L3N6\033[91m┃    \033[1;95m╔═╗╦═╗╔═╗╔╗╔╗╔╗╔╗╔══╦═╗
\033[91m ╰┓▋▋┏╯╯╰━━━━━━╯    \033[1;95m╚═╗╠═╝╠═╣║╚╝║║╚╝║╠═ ╠╦╝
\033[91m╭━┻╮╲┗━━━━╮╭╮       \033[1;95m══╝╩  ╩ ╩╩  ╩╩  ╩╚══╩╚═
\033[91m┃▎▎┃╲╲╲╲╲╲┣━╯   \033[31;0m    «=========๑✧✧๑=========»  \033[1;33m
\033[91m╰━┳┻▅╯╲╲╲╲┃        \033[1;95m╦ ╦╗╦╔═╗╔╦╗╔═╗╦╗╦┌─┐┌─┐┌─┐
\033[91m  ╰━┳┓┏┳┓┏╯        \033[1;95m║ ║║║╚═╗ ║ ╠═╣║║║├─┘├┬┘│ │
\033[91m    ┗┻┛┗┻┛         \033[1;95m╩ ╩╚╝══╝ ╩ ╩ ╩╩╚╝┴  ┴└─└─┘\033[1;93m
╔╦═══════════════════════════════════════════════╗
╠╝  \033[1;30m✬  \033[31;0mAuthor      \033[91m:   \033[1;36mMochammad Nopal Attasya   \033[1;33m║
╠╗  \033[1;30m✬  \033[31;0mEmail       \033[91m:   \033[1;32mnopal7568@gmail.com       \033[1;33m║
║║  \033[1;30m✬  \033[31;0mYoutube     \033[91m:   \033[1;32mPAJAOQ                   \033[1;33m╔╣
╚╬══════════════════════════════════════════════╬╝
\033[1;33m╔╬══════════════════════════════════════════════╬╗
\033[1;33m╠╝\033[91m● \033[92mGunakan Script/Tools Ini Dengan Bijak Apapun\033[1;33m╚╣
\033[1;33m║   \033[92mResikonya Tidak Di Tanggung Oleh Author Nya  \033[1;33m║
\033[1;33m╠════════════════════════════════════════════════╣
\033[1;33m╠══════════════════════════════════════╗         ║
\033[1;33m║               \033[1;33m(\033[92mSPAMMER\033[1;33m)              ║         ║
\033[1;33m╠══════════════════════════════════════╩══╦══════╣"
echo "\33[1;33m║\33[1;32m[1]\33[1;36m Telkomsel                            \33[1;33m║ \33[1;34m(\33[1;32mON\33[1;34m) \33[1;33m║"
echo "\33[1;33m║\33[1;32m[2] \33[1;36mJD.ID                                \33[1;33m║ \33[1;34m(\33[1;32mON\33[1;34m) \33[1;33m║"
echo "\33[1;33m║\33[1;32m[3] \33[1;36mPHD                                  \33[1;33m║ \33[1;34m(\33[1;31mON\33[1;34m) \33[1;33m║"
echo "\33[1;33m║\33[1;32m[4] \33[1;36mTokoPedia                            \33[1;33m║ \33[1;34m(\33[1;31mON\33[1;34m) \33[1;33m║"
echo "\33[1;33m║\33[1;32m[0] \33[1;31mExit.                                \33[1;33m║      \33[1;33m║"
echo "╚═════════════════════════════════════════╩══════╝"
echo ""
read -p "[#]═> " novalattasya

case $novalattasya in
1)
php melwpwmwlwkwmwmwssw
;;
2)
php 829281kosjwowowoskwk
;;
3)
php bom829281kosjwowowoskwkphd
echo "UDAH COID BRO"
sleep 2
sh owowodnlsjxksko8292938919191jososjsoqna
;;
4)
php oeowowowowoowowowowowo9374u3
echo "UDAH COID BRO"
sleep 2
sh owowodnlsjxksko8292938919191jososjsoqna
;;
0)
clear
exit
;;
*)
echo "\33[1;33m[#]═> \33[1;31mCan't Empty\33[1;33m"
sleep 1
sh owowodnlsjxksko8292938919191jososjsoqna
;;
esac
